branch-defaults:
  master:
    environment: dev-env
    group_suffix: null
global:
  application_name: uddoit
  branch: null
  default_ec2_keyname: MyKeyPair
  default_platform: Ruby 2.4 (Puma)
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli2
  repository: null
  sc: git
  workspace_type: Application
